/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <common/pubsub.h>
#include <server/pubsub_svc.h>
#include <server/pubsub_impl.h>
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
pubsubprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		talk join_1_arg;
		talk leave_1_arg;
		sub subscribe_1_arg;
		sub unsubscribe_1_arg;
		pub publish_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case JOIN:
		_xdr_argument = (xdrproc_t) xdr_talk;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) join_1_svc;
		break;

	case LEAVE:
		_xdr_argument = (xdrproc_t) xdr_talk;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) leave_1_svc;
		break;

	case SUBSCRIBE:
		_xdr_argument = (xdrproc_t) xdr_sub;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) subscribe_1_svc;
		break;

	case UNSUBSCRIBE:
		_xdr_argument = (xdrproc_t) xdr_sub;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) unsubscribe_1_svc;
		break;

	case PUBLISH:
		_xdr_argument = (xdrproc_t) xdr_pub;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) publish_1_svc;
		break;

	case PING:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) ping_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

void startRPC() {
	register SVCXPRT *transp;

	pmap_unset (PUBSUBPROG, SUBSUBVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PUBSUBPROG, SUBSUBVERS, pubsubprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PUBSUBPROG, SUBSUBVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PUBSUBPROG, SUBSUBVERS, pubsubprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PUBSUBPROG, SUBSUBVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
