/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <common/pubsub.h>

bool_t
xdr_ip (XDR *xdrs, ip *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXADDR))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_article (XDR *xdrs, article *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXSTRING))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_talk (XDR *xdrs, talk *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->port))
		 return FALSE;
	 if (!xdr_ip (xdrs, &objp->addr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sub (XDR *xdrs, sub *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->port))
		 return FALSE;
	 if (!xdr_ip (xdrs, &objp->addr))
		 return FALSE;
	 if (!xdr_article (xdrs, &objp->art))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pub (XDR *xdrs, pub *objp)
{
	register int32_t *buf;

	 if (!xdr_article (xdrs, &objp->art))
		 return FALSE;
	 if (!xdr_ip (xdrs, &objp->addr))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->port))
		 return FALSE;
	return TRUE;
}
