/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PUBSUB_H_RPCGEN
#define _PUBSUB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXSTRING 120
#define MAXADDR 15

typedef char *ip;

typedef char *article;

struct talk {
	int port;
	ip addr;
};
typedef struct talk talk;

struct sub {
	int port;
	ip addr;
	article art;
};
typedef struct sub sub;

struct pub {
	article art;
	ip addr;
	int port;
};
typedef struct pub pub;

#define PUBSUBPROG 0x20000001
#define SUBSUBVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define JOIN 1
extern  int * join_1(talk *, CLIENT *);
extern  int * join_1_svc(talk *, struct svc_req *);
#define LEAVE 2
extern  int * leave_1(talk *, CLIENT *);
extern  int * leave_1_svc(talk *, struct svc_req *);
#define SUBSCRIBE 3
extern  int * subscribe_1(sub *, CLIENT *);
extern  int * subscribe_1_svc(sub *, struct svc_req *);
#define UNSUBSCRIBE 4
extern  int * unsubscribe_1(sub *, CLIENT *);
extern  int * unsubscribe_1_svc(sub *, struct svc_req *);
#define PUBLISH 5
extern  int * publish_1(pub *, CLIENT *);
extern  int * publish_1_svc(pub *, struct svc_req *);
#define PING 6
extern  int * ping_1(void *, CLIENT *);
extern  int * ping_1_svc(void *, struct svc_req *);
extern int pubsubprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define JOIN 1
extern  int * join_1();
extern  int * join_1_svc();
#define LEAVE 2
extern  int * leave_1();
extern  int * leave_1_svc();
#define SUBSCRIBE 3
extern  int * subscribe_1();
extern  int * subscribe_1_svc();
#define UNSUBSCRIBE 4
extern  int * unsubscribe_1();
extern  int * unsubscribe_1_svc();
#define PUBLISH 5
extern  int * publish_1();
extern  int * publish_1_svc();
#define PING 6
extern  int * ping_1();
extern  int * ping_1_svc();
extern int pubsubprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ip (XDR *, ip*);
extern  bool_t xdr_article (XDR *, article*);
extern  bool_t xdr_talk (XDR *, talk*);
extern  bool_t xdr_sub (XDR *, sub*);
extern  bool_t xdr_pub (XDR *, pub*);

#else /* K&R C */
extern bool_t xdr_ip ();
extern bool_t xdr_article ();
extern bool_t xdr_talk ();
extern bool_t xdr_sub ();
extern bool_t xdr_pub ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PUBSUB_H_RPCGEN */
